name: Build

on: [push]

jobs:
 build:
  name: Build
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    node: ["lts/*"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v5
   - name: 🔩 Setup PNPM
     uses: pnpm/action-setup@v4
     with:
      standalone: true
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v5
     with:
      node-version: ${{ matrix.node }}
      cache: "pnpm"
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Build
     run: pnpm run build
   - name: 📦 Archive production artifacts
     uses: actions/upload-artifact@v4
     with:
      name: build
      path: ./dist
