name: Prettier check

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 check:
  name: Check Format
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v2
   - name: 🚀 Install dependencies
     run: npm i prettier@2.6.2 --no-package-lock --legacy-peer-deps
   - name: 🚀 Check formatting
     run: "npm run format:check"
