name: Prettier format

on:
 workflow_dispatch:

jobs:
 check:
  name: Check Format
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v2
   - name: "🚀 Install dependencies"
     run: npm i prettier@2.6.2 --no-package-lock --legacy-peer-deps
   - name: "🚀 Format code"
     run: "npm run format"
   - name: "🚀 Commit formatted code"
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
      commit_message: "[🚀] Code formatting"
      branch: ${{ github.head_ref }}
      commit_user_name: IgorKowalczykBot
      commit_user_email: "igor.kowalczyk.bot@onet.pl"
