name: Publish [NPM]

on:
 release:
  types: [created]

jobs:
 publish:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write
   id-token: write
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["18.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v3
   - name: 🔩 Setup PNPM
     uses: pnpm/action-setup@v2
     with:
      version: latest
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node }}
      registry-url: "https://registry.npmjs.org"
      cache: "pnpm"
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Build package
     run: pnpm build
   - name: 🚀 Publish package
     run: pnpm publish --access public --no-git-checks --provenance
     env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
