name: Publish [NPM]
on:
 release:
  types: [created]

jobs:
 publish:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
      node-version: 16
   - run: npm install
   - run: |
      rm -f -- ~/.npmrc
      echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc
   - run: npm publish --access public
     env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
